/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 modelStore.gltf --transform 
Files: modelStore.gltf [26.92MB] > C:\Users\User\Desktop\model\modelStore-transformed.glb [3.28MB] (88%)
Author: k3ddesign (https://sketchfab.com/K3DDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gametech-store-c235fdaabedd4699b955f15cee3da2b6
Title: Game/Tech Store
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modelStore-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube022_imagetex003_0.geometry} material={materials['imagetex.003']} position={[-4.715, 1.859, -4.944]} rotation={[0, 1.538, -Math.PI]} scale={[0.118, 0.274, 0.274]} />
      <mesh geometry={nodes.Circle001_Material020_0.geometry} material={materials.PaletteMaterial001} position={[-3.727, 5.116, 4.175]} rotation={[-Math.PI / 2, 0, 0]} scale={0.251} />
      <mesh geometry={nodes.Circle_sign_0.geometry} material={materials.PaletteMaterial002} position={[-0.075, 5.307, -5.943]} rotation={[-Math.PI / 2, 0, 0]} scale={4.872} />
      <mesh geometry={nodes.Cube002_tv_edge_0.geometry} material={materials.PaletteMaterial003} position={[-3.906, 3.515, -5.83]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.761, 0.061, 1]} />
      <mesh geometry={nodes.Cube002_screen_0.geometry} material={materials.screen} position={[-3.906, 3.515, -5.83]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.761, 0.061, 1]} />
      <mesh geometry={nodes.Cube004_screen001_0.geometry} material={materials['screen.001']} position={[3.936, 3.515, -5.83]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.761, 0.061, 1]} />
      <mesh geometry={nodes.room_walls_0.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} scale={5.94} />
      <mesh geometry={nodes.room_floor_0.geometry} material={materials.floor} rotation={[-Math.PI / 2, 0, 0]} scale={5.94} />
      <mesh geometry={nodes.desk_glass001_0.geometry} material={materials.PaletteMaterial004} position={[0, 0, -2.378]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.42, 0.699, 0.699]} />
      <mesh geometry={nodes.Plane007_shelf2_0.geometry} material={materials.shelf2} position={[-4.029, 0.237, 2.082]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cube006_xbox001_0.geometry} material={materials['xbox.001']} position={[-5.68, 4.339, 2.154]} rotation={[Math.PI, 0.447, 0]} scale={0.488} />
      <mesh geometry={nodes.Cube007_ps5_0.geometry} material={materials.material} position={[5.341, 4.392, 3.496]} rotation={[0, 0.908, 0]} scale={0.494} />
      <mesh geometry={nodes.Cube008_g1007_0.geometry} material={materials['g1.007']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1002_0.geometry} material={materials['g1.002']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1006_0.geometry} material={materials['g1.006']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_Material021_0.geometry} material={materials['Material.021']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1008_0.geometry} material={materials['g1.008']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1005_0.geometry} material={materials['g1.005']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1003_0.geometry} material={materials['g1.003']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1004_0.geometry} material={materials['g1.004']} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.Cube008_g1_0.geometry} material={materials.material_40} position={[-3.741, 1.7, 3.589]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.163, 0.23, 0.005]} />
      <mesh geometry={nodes.poster1_poster1_0.geometry} material={materials.poster1} position={[5.878, 2.366, -3.084]} rotation={[0, -Math.PI / 2, 0]} scale={2.501} />
      <mesh geometry={nodes.poster2_poster2_0.geometry} material={materials.poster2} position={[5.878, 2.366, 0.706]} rotation={[0, -Math.PI / 2, 0]} scale={2.501} />
      <mesh geometry={nodes.poster3_poster3_0.geometry} material={materials.poster3} position={[-5.893, 2.366, -1.957]} rotation={[0, -Math.PI / 2, 0]} scale={2.501} />
      <mesh geometry={nodes.poster4_poster4_0.geometry} material={materials.poster4} position={[-5.893, 2.366, 0.918]} rotation={[0, -Math.PI / 2, 0]} scale={2.501} />
      <mesh geometry={nodes.switch_box_0.geometry} material={materials.material_45} position={[-5.484, 3.834, 3.964]} rotation={[Math.PI, 0.167, 0]} scale={[0.272, 0.462, 0.855]} />
      <mesh geometry={nodes.keybouardbox_Material_0.geometry} material={materials.Material} position={[-3.651, 0.502, 3.467]} rotation={[-Math.PI / 2, 0, 1.354]} scale={0.199} />
      <mesh geometry={nodes.charger_Material039_0.geometry} material={materials['Material.039']} position={[-3.649, 1.092, 3.705]} rotation={[-Math.PI / 2, 0, -0.792]} scale={0.115} />
      <mesh geometry={nodes.phonebox_Material040_0.geometry} material={materials['Material.040']} position={[5.223, 3.987, -0.757]} rotation={[-Math.PI / 2, 0, -1.781]} scale={[0.133, 0.085, 0.133]} />
      <mesh geometry={nodes.iphone_Material057_0.geometry} material={materials['Material.057']} position={[-5.13, 4.048, 0.417]} rotation={[-Math.PI / 2, 0, -1.034]} scale={[0.049, 0.107, 0.107]} />
      <mesh geometry={nodes.earbuds_Material059_0.geometry} material={materials['Material.059']} position={[-3.68, 0.448, 1.83]} rotation={[Math.PI, 0.695, 0]} scale={[0.048, 0.154, 0.154]} />
      <mesh geometry={nodes.Cube092_Material060_0.geometry} material={materials['Material.060']} position={[-1.16, 3.923, -4.891]} rotation={[-Math.PI / 2, 0, -1.59]} scale={[0.034, 0.197, 0.197]} />
      <mesh geometry={nodes.xbox011_xbox002_0.geometry} material={materials['xbox.002']} position={[1.703, 2.327, -4.976]} scale={0.406} />
      <mesh geometry={nodes.xbox011_steam001_0.geometry} material={materials['steam.001']} position={[1.703, 2.327, -4.976]} scale={0.406} />
      <mesh geometry={nodes.xbox011_ps001_0.geometry} material={materials['ps.001']} position={[1.703, 2.327, -4.976]} scale={0.406} />
      <mesh geometry={nodes.xbox011_n001_0.geometry} material={materials['n.001']} position={[1.703, 2.327, -4.976]} scale={0.406} />
      <mesh geometry={nodes.xbox011_google001_0.geometry} material={materials['google.001']} position={[1.703, 2.327, -4.976]} scale={0.406} />
      <mesh geometry={nodes.xbox011_apple001_0.geometry} material={materials['apple.001']} position={[1.703, 2.327, -4.976]} scale={0.406} />
      <mesh geometry={nodes.headphones_imagetex_0.geometry} material={materials.imagetex} position={[-0.026, 2.849, -4.882]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.053, 0.135, 0.135]} />
      <mesh geometry={nodes.hp2_imagetex001_0.geometry} material={materials['imagetex.001']} position={[1.071, 2.93, -4.882]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.123, 0.216, 0.216]} />
      <mesh geometry={nodes.Cube021_imagetex002_0.geometry} material={materials['imagetex.002']} position={[1.63, 2.93, -4.882]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.216} />
      <mesh geometry={nodes.PS5_standard001_PS5_Standard001_0.geometry} material={materials['PS5_Standard.001']} position={[3.687, 1.683, -5.526]} scale={0.032} />
      <mesh geometry={nodes.PS5_standard001_ps5_light001_0.geometry} material={materials.PaletteMaterial005} position={[3.687, 1.683, -5.526]} scale={0.032} />
      <mesh geometry={nodes.Cash_Register_Material043_0.geometry} material={materials['Material.043']} position={[-0.974, 1.673, -2.101]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={1.42} />
      <instancedMesh args={[nodes.Cube023_imagetex004_0.geometry, materials.PaletteMaterial003, 6]} instanceMatrix={nodes.Cube023_imagetex004_0.instanceMatrix} />
      <instancedMesh args={[nodes.Cube027_imagetex005_0.geometry, materials.PaletteMaterial003, 5]} instanceMatrix={nodes.Cube027_imagetex005_0.instanceMatrix} />
      <instancedMesh args={[nodes.Cube030_imagetex003_0.geometry, materials['imagetex.003'], 5]} instanceMatrix={nodes.Cube030_imagetex003_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/modelStore-transformed.glb')
