/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 modelRecipe.gltf --transform 
Files: modelRecipe.gltf [48.44MB] > C:\Users\User\Desktop\recipe\modelRecipe-transformed.glb [720.95KB] (99%)
Author: WaajaaH (https://sketchfab.com/WaajaaH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/recipe-book-asset-122bcd25d73b4f349d554925cbe16b16
Title: Recipe Book Asset
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modelRecipe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube7_Gold_0.geometry} material={materials.Gold} />
      <mesh geometry={nodes.pCube4_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/modelRecipe-transformed.glb')
