/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 modelChess.gltf --transform 
Files: modelChess.gltf [736.46KB] > C:\Users\User\Desktop\chess\modelChess-transformed.glb [208.37KB] (72%)
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-board-a0fb4aa0e75649e0991a2571ab70ea44
Title: Chess Board
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modelChess-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['B_Pawn_8_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0.004, 0, 0.023]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.003} />
      <mesh geometry={nodes['W_Bishop_2_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-0.012, 0, 0.028]} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes['Chess_Board_08_-_Default_0'].geometry} material={materials['08_-_Default']} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes['Chess_Board_07_-_Default_0'].geometry} material={materials['07_-_Default']} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes['Chess_Board_03_-_Default_0'].geometry} material={materials['03_-_Default']} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes['Chess_Board_02_-_Default_0'].geometry} material={materials['02_-_Default_0']} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('/modelChess-transformed.glb')
